const normal = {
    番茄: {
        Tulips: true,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    西瓜: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    草莓: {
        Tulips: true,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    蜜瓜: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    芜菁: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: true,
        Days: "较短",
        Seed: 0,
        Price: 0,
    },
    土豆: {
        Tulips: true,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    胡萝卜: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    甘薯: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
}
const synthesize = {
    西茄: {
        Tulips: true,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    莓茄: {
        Tulips: true,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    蜜茄: {
        Tulips: true,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "较长",
        Seed: 0,
        Price: 0,
    },
    西莓: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    西蜜瓜: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    蜜莓: {
        Tulips: true,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    土菁: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    萝菁: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    芜薯: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    土萝卜: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: true,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    土薯: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    胡薯: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    茄菁: {
        Tulips: true,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    土茄: {
        Tulips: true,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    胡茄: {
        Tulips: true,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    甘茄: {
        Tulips: true,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    西菁: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    土西瓜: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    萝瓜: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    甘西瓜: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    芜茄: {
        Tulips: true,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    土莓: {
        Tulips: true,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    胡莓: {
        Tulips: true,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "较长",
        Seed: 0,
        Price: 0,
    },
    草薯: {
        Tulips: true,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    蜜菁: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "较长",
        Seed: 0,
        Price: 0,
    },
    土蜜瓜: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    胡蜜: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    甘蜜瓜: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
}

const rare = {
    珍种1: {
        Tulips: true,
        Pepper: false,
        Amber: false,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种2: {
        Tulips: true,
        Pepper: false,
        Amber: false,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种3: {
        Tulips: false,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种4: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "较长",
        Seed: 0,
        Price: 0,
    },
    珍种5: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种6: {
        Tulips: true,
        Pepper: false,
        Amber: false,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种7: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "较长",
        Seed: 0,
        Price: 0,
    },
    珍种8: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种9: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种11: {
        Tulips: true,
        Pepper: false,
        Amber: false,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种12: {
        Tulips: false,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种13: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种14: {
        Tulips: false,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种15: {
        Tulips: false,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种16: {
        Tulips: true,
        Pepper: false,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种17: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种18: {
        Tulips: false,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种19: {
        Tulips: true,
        Pepper: false,
        Amber: false,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种20: {
        Tulips: false,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种21: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种22: {
        Tulips: false,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种23: {
        Tulips: true,
        Pepper: false,
        Amber: false,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种24: {
        Tulips: false,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种25: {
        Tulips: false,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种26: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: false,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种27: {
        Tulips: false,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种28: {
        Tulips: false,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种29: {
        Tulips: false,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种30: {
        Tulips: false,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "略短",
        Seed: 0,
        Price: 0,
    },
    珍种31: {
        Tulips: false,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种32: {
        Tulips: false,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种33: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种34: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "较长",
        Seed: 0,
        Price: 0,
    },
    珍种35: {
        Tulips: true,
        Pepper: true,
        Amber: false,
        Indigo: false,
        Days: "略长",
        Seed: 0,
        Price: 0,
    },
    珍种36: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "较长",
        Seed: 0,
        Price: 0,
    },
    珍种37: {
        Tulips: false,
        Pepper: false,
        Amber: true,
        Indigo: true,
        Days: "较长",
        Seed: 0,
        Price: 0,
    },
    珍种38: {
        Tulips: true,
        Pepper: false,
        Amber: false,
        Indigo: true,
        Days: "较长",
        Seed: 0,
        Price: 0,
    },
    珍种39: {
        Tulips: false,
        Pepper: true,
        Amber: true,
        Indigo: false,
        Days: "较长",
        Seed: 0,
        Price: 0,
    },
}
const tree = {"桃子": {"Tulips": false, "Pepper": true, "Amber": false, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "橘子": {"Tulips": false, "Pepper": true, "Amber": false, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "葡萄": {"Tulips": false, "Pepper": false, "Amber": true, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "香蕉": {"Tulips": false, "Pepper": true, "Amber": false, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "苹果": {"Tulips": false, "Pepper": false, "Amber": true, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}}
const tree_synthesize = {"桃橘": {"Tulips": false, "Pepper": false, "Amber": true, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "葡桃": {"Tulips": false, "Pepper": false, "Amber": true, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "桃蕉": {"Tulips": false, "Pepper": false, "Amber": false, "Indigo": true, "Days": "", "Seed": 0, "Price": 0}, "苹桃": {"Tulips": false, "Pepper": false, "Amber": true, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "橘萄": {"Tulips": false, "Pepper": true, "Amber": false, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "橘蕉": {"Tulips": false, "Pepper": false, "Amber": false, "Indigo": true, "Days": "", "Seed": 0, "Price": 0}, "苹橘": {"Tulips": false, "Pepper": false, "Amber": false, "Indigo": true, "Days": "", "Seed": 0, "Price": 0}, "葡蕉": {"Tulips": false, "Pepper": true, "Amber": false, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "苹萄": {"Tulips": false, "Pepper": true, "Amber": false, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "苹蕉": {"Tulips": false, "Pepper": false, "Amber": true, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}}
const tree_rare = {"珍树1": {"Tulips": false, "Pepper": false, "Amber": false, "Indigo": true, "Days": "", "Seed": 0, "Price": 0}, "珍树2": {"Tulips": false, "Pepper": true, "Amber": false, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "珍树3": {"Tulips": false, "Pepper": false, "Amber": false, "Indigo": true, "Days": "", "Seed": 0, "Price": 0}, "珍树4": {"Tulips": false, "Pepper": true, "Amber": false, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "珍树5": {"Tulips": false, "Pepper": false, "Amber": true, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "珍树6": {"Tulips": false, "Pepper": false, "Amber": true, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "珍树7": {"Tulips": false, "Pepper": true, "Amber": false, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "珍树8": {"Tulips": false, "Pepper": false, "Amber": true, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}, "珍树9": {"Tulips": true, "Pepper": false, "Amber": false, "Indigo": false, "Days": "", "Seed": 0, "Price": 0}}
